// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func MakeBattlePage(token string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html><head><script src=\"https://unpkg.com/htmx.org@1.9.10\" integrity=\"sha384-D1Kt99CQMDuVetoL1lrYwg5t+9QdHe7NLX/SoJYkXDFfX37iInKRy5xLSi8nO7UC\" crossorigin=\"anonymous\"></script><script src=\"https://cdn.tailwindcss.com\"></script><title>Todo App</title></head><style type=\"text/css\">\r\n    tr.htmx-swapping td {\r\n        opacity: 0;\r\n        transition: opacity 1s ease-out;\r\n    }\r\n</style><body><div class=\"min-h-screen bg-gray-900 flex flex-col items-center justify-start pt-10\" id=\"todolist\"><div class=\"bg-gray-700 shadow rounded-lg p-6 text-gray-50\"><h1 class=\"text-xl font-semibold mb-4 text-green-500\">Todo App</h1><p class=\"mb-6\">Add your todos below and keep track of your progress.</p><form id=\"\" hx-boost=\"true\" hx-post=\"/fire\" hx-swap=\"none\" hx-target=\"this\"><input type=\"text\" name=\"brand\" placeholder=\"Brand\" autocomplete=\"off\"> <input type=\"text\" name=\"make\" placeholder=\"Make\" autocomplete=\"off\"> <input type=\"text\" name=\"model\" placeholder=\"Model\" autocomplete=\"off\"> <input type=\"text\" name=\"year\" placeholder=\"Year\" autocomplete=\"off\"> <input type=\"text\" name=\"imageURL\" placeholder=\"Image Link\" autocomplete=\"off\"> <button class=\"inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 hover:bg-primary/90 h-10 px-4 py-2 mt-4 bg-green-500 text-gray-50\" type=\"submit\">Add Todo\r</button></form></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
